### ISSUE TITLE
Roborock S6 no connection

### ISSUE THREAD

**Issue by Balu0127** [iobroker-community-adapters/ioBroker.mihome-vacuum#148]
Hi

The adapter unfortunately remains on yellow and does not change to green in Iobroker.
Firmware of the Roborok S6 -> 3.5.4_1048

**Comment by dirkhe** [comment]
please try to open your mihome app and waeit a moment

**Comment by Balu0127** [comment]
> please try to open your mihome app and wait a moment

Hi
Why? What is that supposed to help. The mihome adapter remains on yellow in Iobroker.

**Comment by dirkhe** [comment]
It is yellow, because the adapter could Not Connect to the robbi or geh no answer from robbi. Often it is Silver, if the robbi will communicate with Cloud and App. Than the robbi will speak again with the adapter. Than the App could be closed and if you want to remove the Internet Connection from robbi

**Comment by Balu0127** [comment]
Hi

Tried everything App left open, Robi vacuumed. There was no connection. But you gave me a good tip when you reconnect the vacuum cleaner in the WiFi, the adapter will find the vacuum cleaner immediately. Thank you so much!
