### ISSUE TITLE
No MapURL with Roborock S6 MaxV

### ISSUE THREAD

**Issue by AF-112** [iobroker-community-adapters/ioBroker.mihome-vacuum#199]
Object points are created for me, but no MapURL is generated. Map64 and MapURL are empty. Does this only work with a rooted device via Valetudo?

I entered cloud access data and selected the device from the list. Under Settings I have activated Use map from cloud, as described in way 1 to retrieve a map.

Have a Roborock S6 MaxV, connected with MiHome App on German Server.

**Comment by radebold** [comment]
I have the same issue with same settings as AF-112.
Any news in this topic ?

My fw is 3.5.8_5156

**Comment by om2804** [comment]
Roborock S50 same
used to work

**Comment by jankap** [comment]
Same for S5 Max. Anything we can do to debug?

**Comment by M1cS0w** [comment]
Hi,

since some days, or weeks, the map is without function.
First I have seen, that the map is not longer update.

I have change the setting for the new map, then tried to get the map as new. But no, there don't come any new map information. In the log there is still:

`
mihome-vacuum.0 | 2021-03-26 10:28:59.540 | warn | (7954) Could not receive Mappointer, giving up
-- | -- | -- | --
mihome-vacuum.0 | 2021-03-26 10:28:51.040 | info | (7954) trigger cleaning segment 16
mihome-vacuum.0 | 2021-03-26 10:28:19.304 | info | (7954) create states for water box filter
mihome-vacuum.0 | 2021-03-26 10:28:19.304 | info | (7954) create states for water box
mihome-vacuum.0 | 2021-03-26 10:26:39.681 | info | (7954) set nächster Timer: Nicht verfügbar
mihome-vacuum.0 | 2021-03-26 10:26:39.270 | info | (7954) Connected
mihome-vacuum.0 | 2021-03-26 10:26:39.255 | info | (7954) connecting, this can take up to 10 minutes ...
mihome-vacuum.0 | 2021-03-26 10:26:39.196 | info | (7954) New generation or new fw(3.5.8,5690) detected, create new states goto and zoneclean
mihome-vacuum.0 | 2021-03-26 10:26:39.174 | info | (7954) Create state clean_home for controlling by cloud adapter
mihome-vacuum.0 | 2021-03-26 10:26:39.173 | info | (7954) Expert mode disabled, states deleted
mihome-vacuum.0 | 2021-03-26 10:26:39.155 | info | (7954) starting. Version 2.1.1 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v12.21.0, js-controller: 3.2.16
`

And since some weeks, the adapter only will be green, when I started the app.

**Comment by MeisterTR** [comment]
please post a log debug log to see. i have a s7 and it works greate

**Comment by om2804** [comment]
Fixed for me after update with git repo

**Comment by AF-112** [comment]
Unfortunately, the map still does not work for me.

The following error message is output in the log.

 (3396) Error when mapurl: {"receiving": - 1, "message": "deny", "result": null}

![2021-05-03 22_55_55-Window](https://user-images.githubusercontent.com/55047165/116932590-c06be100-ac62-11eb-9a19-a8ab04b07766.png)

**Comment by MeisterTR** [comment]
Please try 3.1.5 from git

**Comment by M1cS0w** [comment]
Hello, after updating from git, it works. new Rooms, but also the map is now also visible.
