### ISSUE TITLE
Bekomme keine Geräte -  stattdessen "please activate Instance"

### ISSUE THREAD

**Issue by FelixZiesel** [iobroker-community-adapters/ioBroker.mihome-vacuum#258]
Hi,

ich versuche gerade den Adapter einzurichten. Sobald ich versuche mich über Cloud anzumelden und die Geräte abzufragen erhalte ich als Meldung "Please activate instance". Ein Start der Instanz ist jeoch nicht möglich - dazu fehlt mir ja das Token.
Was mach ich falsch?

BTW: verwendete Version ist 2.1.1

Grüße,
Felix

**Comment by MeisterTR** [comment]
Du gehst anstatt auf speichern, auf abbrechen, und startest dann erst die Instanz

**Comment by Eugen981** [comment]
hi, wie hast du es gelöst?
Ich bekomme meine  mihome-vacuum.0 Instanz nicht zum Laufen.. :(  Die ist dauern rot und GET DIVICES kann ich nicht hinzufügen , kommt Fehlermeldung "please activate Instance"

LOG:
<html>
<body>


  |   |   |  
-- | -- | -- | --
host.DESKTOP-72IGS8J(SmartHome) | 2022-01-31 12:28:46.761 | info | instance system.adapter.info.0 started with pid 14980
mihome.0 | 2022-01-31 12:28:36.347 | error | (10396) no key defined. Only read is possible
host.DESKTOP-72IGS8J(SmartHome) | 2022-01-31 12:28:16.699 | info | Restart adapter system.adapter.info.0 because enabled
host.DESKTOP-72IGS8J(SmartHome) | 2022-01-31 12:28:16.699 | info | instance system.adapter.info.0 terminated with code 0 (NO_ERROR)
host.DESKTOP-72IGS8J(SmartHome) | 2022-01-31 12:28:16.698 | error | Caught by controller[0]: at tryCatcher (C:\Program Files\iobroker\SmartHome\node_modules\standard-as-callback\built\utils.js:11:23)
host.DESKTOP-72IGS8J(SmartHome) | 2022-01-31 12:28:16.698 | error | Caught by controller[0]: at client.evalsha (C:\Program Files\iobroker\SmartHome\node_modules\iobroker.js-controller\lib\objects\objectsInRedis.js:2243:17)
host.DESKTOP-72IGS8J(SmartHome) | 2022-01-31 12:28:16.698 | error | Caught by controller[0]: at adapter.objects.getObjectView (C:\Program Files\iobroker\SmartHome\node_modules\iobroker.info\main.js:264:21)
host.DESKTOP-72IGS8J(SmartHome) | 2022-01-31 12:28:16.698 | error | Caught by controller[0]: at instances (C:\Program Files\iobroker\SmartHome\node_modules\iobroker.info\main.js:160:26)
host.DESKTOP-72IGS8J(SmartHome) | 2022-01-31 12:28:16.698 | error | Caught by controller[0]: at Array.forEach (<anonymous>)
host.DESKTOP-72IGS8J(SmartHome) | 2022-01-31 12:28:16.698 | error | Caught by controller[0]: at messages.forEach.message (C:\Program Files\iobroker\SmartHome\node_modules\iobroker.info\main.js:172:57)
host.DESKTOP-72IGS8J(SmartHome) | 2022-01-31 12:28:16.698 | error | Caught by controller[0]: at Array.forEach (<anonymous>)
host.DESKTOP-72IGS8J(SmartHome) | 2022-01-31 12:28:16.698 | error | Caught by controller[0]: at Object.keys.forEach.key (C:\Program Files\iobroker\SmartHome\node_modules\iobroker.info\main.js:185:46)
host.DESKTOP-72IGS8J(SmartHome) | 2022-01-31 12:28:16.698 | error | Caught by controller[0]: at checkConditions (C:\Program Files\iobroker\SmartHome\node_modules\iobroker.info\main.js:138:25)
host.DESKTOP-72IGS8J(SmartHome) | 2022-01-31 12:28:16.698 | error | Caught by controller[0]: at checkVersion (C:\Program Files\iobroker\SmartHome\node_modules\iobroker.info\main.js:223:23)
host.DESKTOP-72IGS8J(SmartHome) | 2022-01-31 12:28:16.698 | error | Caught by controller[0]: TypeError: Cannot read property 'split' of undefined
info.0 | 2022-01-31 12:28:16.125 | info | (2400) Terminated (NO_ERROR): Without reason
info.0 | 2022-01-31 12:28:16.125 | info | (2400) terminating
info.0 | 2022-01-31 12:28:16.123 | info | (2400) cleaned everything up...
info.0 | 2022-01-31 12:28:16.122 | error | (2400) TypeError: Cannot read property 'split' of undefined at checkVersion (C:\Program Files\iobroker\SmartHome\node_modules\iobroker.info\main.js:223:23) at checkConditions (C:\Program Files
info.0 | 2022-01-31 12:28:16.122 | error | (2400) uncaught exception: Cannot read property 'split' of undefined
info.0 | 2022-01-31 12:28:16.075 | info | (2400) Popup news was read...
info.0 | 2022-01-31 12:28:11.861 | info | (2400) starting. Version 1.5.6 in C:/Program Files/iobroker/SmartHome/node_modules/iobroker.info, node: v10.17.0
host.DESKTOP-72IGS8J(SmartHome) | 2022-01-31 12:28:09.877 | info | instance system.adapter.info.0 started with pid 2400


</body>
</html>

**Comment by Diginix** [comment]
Dein Log enthält nur Fehler vom info Adapter.
Deine node Version sollte mal auf 12 oder 14 aktualisiert werden. K.a. wie das bei Windows läuft.
