### ISSUE TITLE
[dreame.vacuum.p2029] Support Dreame Bot L10 pro

### ISSUE THREAD

**Issue by volkerrichert** [iobroker-community-adapters/ioBroker.mihome-vacuum#292]
Add support for Dreame Bot L10 pro

mihome-vacuum.0 | 2021-05-13 10:53:53.806 | debug | (12040) Receive <<< Helo <<< 2131002000000000175c9e43609ce921ffffffffffffffffffffffffffffffff
-- | -- | -- | --
mihome-vacuum.0 | 2021-05-13 10:53:43.823 | warn | (12040) Model dreame.vacuum.p2029 not supported! Please open issue on git: https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/issues
mihome-vacuum.0 | 2021-05-13 10:53:43.822 | debug | (12040) DeviceModel selected to: dreame.vacuum.p2029
mihome-vacuum.0 | 2021-05-13 10:53:43.821 | debug | (12040) Get Device data from robot..
mihome-vacuum.0 | 2021-05-13 10:53:43.821 | debug | (12040) Get Device data..0
mihome-vacuum.0 | 2021-05-13 10:53:43.820 | debug | (12040) GETMODELFROMAPI:Data: {"partner_id":"","id":1,"code":0,"message":"ok","result":{"hw_ver":"Linux","fw_ver":"3.5.8_1052","ap":{"ssid":"IoT","bssid":"12:9F:C2:AA:53:2B","rssi":-62},"netif":{"loca
mihome-vacuum.0 | 2021-05-13 10:53:43.820 | debug | (12040) MIIO RECIVE: {"partner_id":"","id":1,"code":0,"message":"ok","result":{"hw_ver":"Linux","fw_ver":"3.5.8_1052","ap":{"ssid":"IoT","bssid":"12:9F:C2:AA:53:2B","rssi":-62},"netif":{"localIp":"192
mihome-vacuum.0 | 2021-05-13 10:53:43.808 | debug | (12040) Message= {"id":1,"method":"miIO.info"}
mihome-vacuum.0 | 2021-05-13 10:53:43.806 | debug | (12040) GETMODELFROMAPI: objModel: {"val":"dreame.vacuum.p2029","ack":true,"ts":1620888600915,"q":0,"from":"system.adapter.mihome-vacuum.0","user":"system.user.admin","lc":1620888467834}
mihome-vacuum.0 | 2021-05-13 10:53:43.802 | debug | (12040) MAIN: Connected to device, try to get model..
mihome-vacuum.0 | 2021-05-13 10:53:43.801 | debug | (12040) Receive <<< Helo <<< 2131002000000000175c9e43609ce917ffffffffffffffffffffffffffffffff
mihome-vacuum.0 | 2021-05-13 10:53:43.784 | debug | (12040) server started on 0.0.0.0:53421
mihome-vacuum.0 | 2021-05-13 10:53:43.781 | info | (12040) IOT disabled, delete state
mihome-vacuum.0 | 2021-05-13 10:53:43.777 | debug | (12040) MIIO: Config: ip:192.168.120.71 token: XXXX
mihome-vacuum.0 | 2021-05-13 10:53:43.776 | debug | (12040) Create State for deviceInfowifi_signal
mihome-vacuum.0 | 2021-05-13 10:53:43.776 | debug | (12040) Create State for deviceInfofw_ver
mihome-vacuum.0 | 2021-05-13 10:53:43.775 | debug | (12040) Create State for deviceInfomodel
mihome-vacuum.0 | 2021-05-13 10:53:43.775 | debug | (12040) Create State for deviceInfomac

THX,

Volker

**Comment by Sepalod** [comment]
any update or plan to add the support of Dreame l10 pro to the iobroker adapter?

**Comment by daes10** [comment]
> Add support for Dreame Bot L10 pro

Still no Support for it?

**Comment by cgajdzik** [comment]
No update yet?

**Comment by Sepalod** [comment]
No update yet?

**Comment by daes10** [comment]
I made the integration througt Valetudo.

**Comment by Sepalod** [comment]
> I made my integration with Valetudo.

sounds interesting. Do you have more insights about the whole setup? can it be integrated into IObroker?

**Comment by daes10** [comment]
Yes, of course. But i need a lot of finetune to work. Now everything works just fine. But i have no out of the box solution to copy and paste. A lot of the things i created myself.

The Setup:
1. I rooted the robot
2. I flashed valetudo software on the robot (Now you can control the robot just thought the valetudo web interface)
3. Then i integrated the robot thought MQTT. My way goes from MQTT to Nodered and then to the iobroker. But you can directly go from the Robot thought MQTT to iobroker.
4. And lastly i make all the automations: Automatic Cleaning, Selected Rooms Cleaning in VIS in the right order and a bunch of other stuff....

I hope i gave you an feeling of how my system looks like and how you can achieve it hopefully ;)

**Comment by m50434** [comment]
Hi @daes10 ,
I have also a L10 Pro. I already rooted, flashed and installed valetudo. Now I want to integrate the L10 Pro in IoBroker like you did.

For using MQTT, Valetudo have some recommodations: 
"Valetudo recommends the use of the Eclipse Mosquitto MQTT Broker, which is FOSS, has a tiny resource footprint and is part of basically every GNU/Linux distribution. 
If you're experiencing problems regarding MQTT, make sure to try Mosquitto since some other MQTT brokers only implement a subset of the MQTT spec, which often leads to issues when used with Valetudo."

So do you use just the MQTT-Broker in IoBroker or do you have a "special MQTT -config" in use?

Thanks.

**Comment by daes10** [comment]
Sry for not answering.... I had a lot of studywork.

Yes, I have set up a MQTT Eclipse Mosquitto Broker at my own. I prefer to use a seperate Broker. So that ioBroker and MQTT or not on the same machine. So when i have any issues a can update they separately. The second reason for me is: the Broker has more Features, because i have the newest Update from Mosquitto. ioBroker not Update the adapter so rapid.

But i think its a personal preference.

The second question about the control...

I made al controls at my own in NodeRed and pls don't use Homie Integration. You can, but I had not a good experience, when i tried it. I think its easier through NodeRed or something.
When you want to discuss more,  pls let me know in a PN.
