### ISSUE TITLE
Map doesnt work

### ISSUE THREAD

**Issue by ibizastyler** [iobroker-community-adapters/ioBroker.mihome-vacuum#366]
Hi,

unfortunately the map doesn't load anymore.
Within the objects, map64 and mapurl are empty (NULL).

It has stopped working around x-mas 2020, but i thought, it will work again if i am updating the admin adapter, js controller, etc. and the newest beta of the vacuum adapter.
Unfortunately, it wasn't the case.

Iobroker is running in a synology docker. Therefore, i tried to install canvas within the container bash.
It did something, but it still doesn't work.

Is there any workaround? I also reinstalled a new instance, but it doesnt work either.

thanks a lot in advance!

**Comment by stonemaan** [comment]
same here. on both Roborock S6 (valetudo) and S5 max (Xiaomi Cloud). Objects map url and map64 show (NULL)
Thanks in advance

**Comment by MeisterTR** [comment]
Did you re-type tyour password? After change from 2.x to 3.x

**Comment by stonemaan** [comment]
Worked with Xiaomi-Cloud - but not with Valetudo. Any suggestions?

**Comment by MeisterTR** [comment]
Valetudo is not supported anymore because the map Format from valetudo has changed a few month ago

**Comment by emre-54** [comment]
Hello, since more than 2 weeks the map of my roborock s6 maxV is not updating. All the other datas are working well. It is conected by xiaomi cloud. Any suggestions?

**Comment by darkdevil373** [comment]
Same here no Update since august

**Comment by Siggi0904** [comment]
Same here, datapoints aren't filled.

Log:
`mihome-vacuum.0 | 2021-11-07 14:58:31.955 | warn | State "mihome-vacuum.0.cleanmap.mapStatus" has no existing object, this might lead to an error in future versions
mihome-vacuum.0 | 2021-11-07 14:58:31.882 | warn | State "mihome-vacuum.0.cleanmap.actualMap" has no existing object, this might lead to an error in future versions
mihome-vacuum.0 | 2021-11-07 14:41:04.147 | warn | State "mihome-vacuum.0.cleanmap.mapStatus" has no existing object, this might lead to an error in future versions
mihome-vacuum.0 | 2021-11-07 14:41:04.115 | warn | State "mihome-vacuum.0.cleanmap.actualMap" has no existing object, this might lead to an error in future versions
`

**Comment by kschaumann** [comment]
Iobroker Admin: v5.1.25
Node.js v14.17.6
NPM 6.14.15
JSController: 3.3.15
mihome-vaccuum: v3.3.1
FW: 3.5.7_002008

In my case, only the "Map"-Fields are not updated anymore. 
For examle, the field _mihome-vacuum.0.info.battery_ is updated as expected, also any other Field I checked. 
But the relevant fields under mihome-vacuum.0.cleanmap does not get any update. Only _mihome-vacuum.0.cleanmap.mapStatus_ is updated always with "WithSegments" as value. 

I have found out, that the cloud access might be complicated as in past. As I have opened the map in the FlowFac app, I get some "messages" like "Verify mailaddress" or smth. 

To recheck, if changed my password in the cloud, retype it in FlowFac (Map is working) and in the Adapter. But the Adapter does not update the map fields. Also by forceing update via _mihome-vacuum.0.cleanmap.loadMap_

I have now deleted the Adapter and reinstalled, the Map was initial created and the content is correct. But there is no update anymore during the robot is cleaning. 

Sometimes the logfile show these messages here: 

mihome-vacuum.0 | 2021-11-09 09:47:11.909 | warn | No Answer for DeviceModel use model from Config
mihome-vacuum.0 | 2021-11-09 09:47:11.908 | warn | No Answer for DeviceModel use old one
mihome-vacuum.0 | 2021-11-09 09:47:11.907 | warn | YOUR DEVICE IS CONNECTED BUT DID NOT ANSWER YET - CONNECTION CAN TAKE UP TO 10 MINUTES - PLEASE BE PATIENT AND DO NOT TURN THE ADAPTER OFF

but some time later, the battery state is updated, the Map not.

I have the loglevel in DEBUG, but could not found any helpful info:

Source | Date | level | Message
-- | -- | -- | --
mihome-vacuum.0 | 2021-11-09 09:54:20.940 | info | Map selected create states...
mihome-vacuum.0 | 2021-11-09 09:54:20.771 | info | settest next timer: not available
mihome-vacuum.0 | 2021-11-09 09:54:20.194 | info | select standard vacuum protocol....
mihome-vacuum.0 | 2021-11-09 09:54:20.170 | warn | No Answer for DeviceModel use model from Config
mihome-vacuum.0 | 2021-11-09 09:54:20.170 | warn | No Answer for DeviceModel use old one
mihome-vacuum.0 | 2021-11-09 09:54:20.169 | warn | YOUR DEVICE IS CONNECTED BUT DID NOT ANSWER YET - CONNECTION CAN TAKE UP TO 10 MINUTES - PLEASE BE PATIENT AND DO NOT TURN THE ADAPTER OFF
mihome-vacuum.0 | 2021-11-09 09:54:10.117 | info | IOT enabled, create state
mihome-vacuum.0 | 2021-11-09 09:54:09.987 | info | starting. Version 3.3.1 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v14.17.6, js-controller: 3.3.15
mihome-vacuum.0 | 2021-11-09 09:54:09.923 | info | Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
mihome-vacuum.0 | 2021-11-09 09:53:35.373 | info | create states for water box
mihome-vacuum.0 | 2021-11-09 09:53:35.335 | info | change states from State control.fan_power
mihome-vacuum.0 | 2021-11-09 09:53:16.660 | info | Room array empty... generate from mapdata.. [[1,"room1"],[2,"room2"],[3,"room3"],[4,"room4"],[20,"room20"],[18,"room18"],[16,"room16"],[5,"room5"],[6,"room6"],[17,"room17"],[19,"room19"]]
mihome-vacuum.0 | 2021-11-09 09:53:15.293 | info | create state for carpet_mode
mihome-vacuum.0 | 2021-11-09 09:52:32.303 | info | Map selected create states...
mihome-vacuum.0 | 2021-11-09 09:52:32.151 | info | settest next timer: not available
mihome-vacuum.0 | 2021-11-09 09:52:31.621 | info | select standard vacuum protocol....
mihome-vacuum.0 | 2021-11-09 09:52:31.601 | warn | No Answer for DeviceModel use model from Config
mihome-vacuum.0 | 2021-11-09 09:52:31.600 | warn | No Answer for DeviceModel use old one
mihome-vacuum.0 | 2021-11-09 09:52:31.600 | warn | YOUR DEVICE IS CONNECTED BUT DID NOT ANSWER YET - CONNECTION CAN TAKE UP TO 10 MINUTES - PLEASE BE PATIENT AND DO NOT TURN THE ADAPTER OFF
mihome-vacuum.0 | 2021-11-09 09:52:21.554 | info | IOT enabled, create state
mihome-vacuum.0 | 2021-11-09 09:52:21.417 | info | starting. Version 3.3.1 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v14.17.6, js-controller: 3.3.15

**Comment by Ilovegym66** [comment]
I solved the problem with create a new password in the app / website from xiaomi. Than I must deinstall all my 4 Mihome-Vacuum Instances, install it new, configure new and now it works fine. The map is updated everytime and works fine.
Hopefully it stay as it is now for a while..

**Comment by kschaumann** [comment]
> I solved the problem with create a new password in the app / website from xiaomi. Than I must deinstall all my 4 Mihome-Vacuum Instances, install it new, configure new and now it works fine. The map is updated everytime and works fine. Hopefully it stay as it is now for a while..

I tried also changing the PW and De- and Reinstall, but the Map is only updated by restart of the Adapter, not periodically.

**Comment by Ilovegym66** [comment]
for me it works now fine, I got an actual map of every of my 4 robots after some seconds.

**Comment by kschaumann** [comment]
Might there be a general Problem with the MAP Feature in the Service? 
Since today I get the Map in none case as normal: 
 - iobroker: as described here
 - FloleFac: Error "Login or Server incorrect", but today morning it works as before, perfect! 
 - Official App: Map is updated only every 1-5 minutes

Is it possible that something general changes in the cloud?

**Comment by florian1984** [comment]
With S7 and Version 3.3.1  node: v14.18.1, js-controller: 3.3.19 => when activate Map in settings the map sometimes get rendered but the adapter crash all the time: 

`
host.raspberrypi | 2021-11-24 15:10:27.671 | info | instance system.adapter.mihome-vacuum.0 terminated with code NaN ()
-- | -- | -- | --
host.raspberrypi | 2021-11-24 15:10:27.665 | warn | instance system.adapter.mihome-vacuum.0 terminated due to SIGSEGV
`

On Node12 it worked without any issue.

=> fully reinstalled, rebuild, fix, .... everything done. same thing happens on new installation ....

**Comment by Farmer-cb** [comment]
bei mir funktioniert auch schon seit längerem die Map nicht mehr.
Ein neues Passwort hat auch nix geholfen

**Comment by Siggi0904** [comment]
Same here,
get the following message at adapter start:
`
mihome-vacuum.0 | 2021-11-29 17:18:54.568 | warn | State "mihome-vacuum.0.cleanmap.actualMap" has no existing object, this might lead to an error in future versions
`

**Comment by Strobelix80** [comment]
After upgrading to Nodejs 14 a adapter rebuild solves this issue in my case

iobroker rebuild adaptername --install

**Comment by Siggi0904** [comment]
Hi, what was fixed with rebuild?

**Comment by Strobelix80** [comment]
> Hi, what was fixed with rebuild?

Sorry. Map seems to work, but i‘m wrong. No maps are working

**Comment by pphlwmarcel** [comment]
Map is not working at the moment. Cannot say for sure but seems that the issue started with upgrade from node.js 12 to node.js 14 on iobroker.

Error log below:

mihome-vacuum.0 | 2021-12-31 14:18:14.285 | warn | Get Error when receiving map url: Error: getaddrinfo ENOTFOUND de.api.io.mi.com
-- | -- | -- | --
mihome-vacuum.0 | 2021-12-31 14:18:04.235 | warn | Get Error when receiving map url: Error: getaddrinfo ENOTFOUND de.api.io.mi.com
mihome-vacuum.0 | 2021-12-31 14:17:57.105 | warn | Get Error when receiving map url: Error: Client network socket disconnected before secure TLS connection was established
mihome-vacuum.0 | 2021-12-31 14:17:54.174 | warn | Get Error when receiving map url: Error: getaddrinfo ENOTFOUND de.api.io.mi.com
mihome-vacuum.0 | 2021-12-31 14:17:23.170 | warn | Get Error when receiving map url: Error: Client network socket disconnected before secure TLS connection was established
mihome-vacuum.0 | 2021-12-31 14:16:03.594 | warn | Get Error when receiving map url: Error: getaddrinfo ENOTFOUND de.api.io.mi.com
mihome-vacuum.0 | 2021-12-31 14:14:23.385 | warn | Get Error when receiving map url: Error: read ECONNRESET
mihome-vacuum.0 | 2021-12-31 14:14:13.113 | warn | Get Error when receiving map url: Error: Client network socket disconnected before secure TLS connection was established
mihome-vacuum.0 | 2021-12-31 14:14:08.728 | warn | Get Error when receiving map url: Error: Client network socket

**Comment by Strobelix80** [comment]
> Map is not working at the moment. Cannot say for sure but seems that the issue started with upgrade from node.js 12 to node.js 14 on iobroker.
> 
> Error log below:
> 
> mihome-vacuum.0	2021-12-31 14:18:14.285	warn	Get Error when receiving map url: Error: getaddrinfo ENOTFOUND de.api.io.mi.com
> mihome-vacuum.0	2021-12-31 14:18:04.235	warn	Get Error when receiving map url: Error: getaddrinfo ENOTFOUND de.api.io.mi.com
> mihome-vacuum.0	2021-12-31 14:17:57.105	warn	Get Error when receiving map url: Error: Client network socket disconnected before secure TLS connection was established
> mihome-vacuum.0	2021-12-31 14:17:54.174	warn	Get Error when receiving map url: Error: getaddrinfo ENOTFOUND de.api.io.mi.com
> mihome-vacuum.0	2021-12-31 14:17:23.170	warn	Get Error when receiving map url: Error: Client network socket disconnected before secure TLS connection was established
> mihome-vacuum.0	2021-12-31 14:16:03.594	warn	Get Error when receiving map url: Error: getaddrinfo ENOTFOUND de.api.io.mi.com
> mihome-vacuum.0	2021-12-31 14:14:23.385	warn	Get Error when receiving map url: Error: read ECONNRESET
> mihome-vacuum.0	2021-12-31 14:14:13.113	warn	Get Error when receiving map url: Error: Client network socket disconnected before secure TLS connection was established
> mihome-vacuum.0	2021-12-31 14:14:08.728	warn	Get Error when receiving map url: Error: Client network socket

This is a server error from xiaomi and not adapter related

**Comment by MeisterTR** [comment]
yes it was a server errror but now the adapter did not work anymore. have to check if they changed the serversettings

**Comment by kschaumann** [comment]
> yes it was a server errror but now the adapter did not work anymore. have to check if they changed the serversettings

Last Update of any of the Status fields was done at 2021-12-28 13:43. 
Restart of robot and/or adapter does not help. FloleVac also does not work anymore. The official app is still working and show status an map. So for me it looks like that the server api changed or smth. 

Log of Restart of Adapter: 

mihome-vacuum.0 | 2022-01-13 15:09:01.531 | debug | Helo message Timeout
-- | -- | -- | --
mihome-vacuum.0 | 2022-01-13 15:08:49.528 | debug | Helo message Timeout
mihome-vacuum.0 | 2022-01-13 15:08:37.527 | debug | Helo message Timeout
mihome-vacuum.0 | 2022-01-13 15:08:25.524 | debug | Helo message Timeout
mihome-vacuum.0 | 2022-01-13 15:08:13.521 | debug | Helo message Timeout
mihome-vacuum.0 | 2022-01-13 15:08:01.518 | debug | Helo message Timeout
mihome-vacuum.0 | 2022-01-13 15:07:59.514 | debug | server started on 0.0.0.0:53421
mihome-vacuum.0 | 2022-01-13 15:07:59.509 | info | IOT enabled, create state
mihome-vacuum.0 | 2022-01-13 15:07:59.504 | debug | MIIO: Config: ip:192.168.XX.YYY token: 756e6d55ABCDEFGEHIJKd76454a
mihome-vacuum.0 | 2022-01-13 15:07:59.503 | debug | Create State for deviceInfowifi_signal
mihome-vacuum.0 | 2022-01-13 15:07:59.502 | debug | Create State for deviceInfofw_ver
mihome-vacuum.0 | 2022-01-13 15:07:59.501 | debug | Create State for deviceInfomodel
mihome-vacuum.0 | 2022-01-13 15:07:59.500 | debug | Create State for deviceInfomac
mihome-vacuum.0 | 2022-01-13 15:07:59.499 | debug | Create State for deviceInfo
mihome-vacuum.0 | 2022-01-13 15:07:59.462 | debug | load Map creator... true
mihome-vacuum.0 | 2022-01-13 15:07:59.362 | info | starting. Version 3.3.1 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v14.17.6, js-controller: 3.3.22



that's all... in Debug Level!

**Comment by Creekhail** [comment]
Ich kann mich leider mit in die Reihe stellen - seit einiger Zeit aktualisiert sich die Karte nicht mehr.
Gerätemodell Roborock S6 - die restlichen Daten werden wie gewohnt gesynct. Originalapp von Xiaomi zeigt die Karte.

**Comment by kschaumann** [comment]
I can now say, that after this period of time (Last Update at 2021-12-28) and today a reentry of the token and the ip of the roborock I get an Update of the map, not the "Helo message Timeout". 
Which now seams to me like the Adapter could not connect to the Roborock in the WLAN, not to the cloud!! 
I Switched my fritz.box in dez/2021 to a new Version (now 7590, was 7490), but the IP of the Roborock (and also of iobroker) stay the same. Maybe this was the reason for the connection problems and for the "helo" message. 

So my tipp is, reenter the token and ip in the manual area of the adapter-settings and wait some time. 

The Update of the map is now not as "live" as is was in early 2021, but the map is updated.

**Comment by Creekhail** [comment]
Ich habe inzwischen einen neuen S7 MaxV angeschlossen - der hat leider das gleiche Problem: Die Map-Daten werden leider nicht geladen.
